version: 2
jobs:
  test:
    working_directory: ~/flask_app
    docker:
    - image: python:3.5.2
    steps:
    - checkout
    - restore_cache:
        key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
    - run:
        command: |
          pip --cache-dir=.pip-flask_app install -r requirements.txt
    - save_cache:
        key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
        paths:
        - .pip-flask_app
    - run:
        command: |
          python test/hello_test.py
workflows:
  version: 2
  workflow:
    jobs:
    - test
